version: '3.8'

services:
  postgres:
    image: postgres:16  # Usamos la versión 16 de Postgres
    container_name: trading-db
    environment:
      POSTGRES_DB: trading_journal  # Nombre de la base de datos a crear
      POSTGRES_USER: user_trading   # Usuario
      POSTGRES_PASSWORD: password123 # Contraseña (segura solo para dev)
    ports:
      - "5432:5432" # Expone el puerto 5432 de tu PC